# Generated by Django 5.0.4 on 2024-04-12 14:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('created_at', models.DateField(verbose_name=datetime.date)),
                ('updated_at', models.DateField(verbose_name=datetime.date)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=255)),
                ('amount', models.BigIntegerField()),
                ('currency', models.CharField(max_length=255)),
                ('created_at', models.DateField(verbose_name=datetime.date)),
                ('updated_at', models.DateField(verbose_name=datetime.date)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('user_type', models.CharField(max_length=255)),
                ('groups_joined', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateField(verbose_name=datetime.date)),
                ('updated_at', models.DateField(verbose_name=datetime.date)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.BigIntegerField()),
                ('product_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('product_owner', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateField(verbose_name=datetime.date)),
                ('updated_at', models.DateField(verbose_name=datetime.date)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='body.payment')),
                ('liked_by', models.ManyToManyField(blank=True, null=True, related_name='liked_products', to='body.user')),
            ],
        ),
        migrations.CreateModel(
            name='Savatcha',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(verbose_name=datetime.date)),
                ('updated_at', models.DateField(verbose_name=datetime.date)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.user')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('product_amount', models.IntegerField()),
                ('price', models.CharField(max_length=255)),
                ('total_amount', models.IntegerField()),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.user')),
            ],
        ),
    ]
