# Generated by Django 5.0.4 on 2024-04-12 15:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='liked_by',
        ),
        migrations.CreateModel(
            name='liked',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateField(verbose_name=datetime.date)),
                ('updated_at', models.DateField(verbose_name=datetime.date)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.user')),
            ],
        ),
    ]
