# Generated by Django 5.0.4 on 2024-04-12 17:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0005_product_photo_or_video_alter_product_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasehistory',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='updated_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
