# Generated by Django 5.0.4 on 2024-04-12 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0006_alter_purchasehistory_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='body.category'),
        ),
        migrations.AlterField(
            model_name='purchasehistory',
            name='product_amount',
            field=models.SmallIntegerField(),
        ),
    ]
