# Generated by Django 5.0.4 on 2024-04-17 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0008_alter_savatcha_user_alter_liked_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='payment',
        ),
    ]
